#!/bin/bash
### Accept ID, cost and insert into db_details
##Exit codes
##	0:	Normal termination
##	1:	Invalid paramters
##	2:	Invalid id, must be integer
##	3:	Invalid price, mustbe integer
##	4:	ID is not found in the master


if [ ! $# -eq 2 ]
then
	echo "Invalid paramters"
	echo "Usage: ./sc14 ID Price"
	exit 1
fi

########## Check if id, and price are integers
temp1="^[0-9]+$"
ID=$1
PRICE=$2
if ! [[ $ID =~ $temp1 ]]
then
	echo "Invalid ID, must be an integer"
	exit 2
fi
if ! [[ $PRICE =~ $temp1 ]]
then
        echo "Invalid price, must be an integer"
        exit 3
fi

########### Check if ID is exists in db_info or no
QUERY=$(mysql -u non -pJava123$ -NB -e "select * from bash.stinfo where id = $ID")
if [ -z "$QUERY" ]
then
	echo "Error: db_stinfo has no ID, can not insert"
	exit 4
fi
#####################################33
## insert in DB
mysql -u non -pJava123$  -e "insert into bash.stdetails values($ID, '$PRICE')"
echo "$ID inserted into db_details"
exit 0
