#!/bin/bash
########### Script accepts ID, and prints the details and sum
##Exit code:
##	0: Normal termination
##	1: Invalid paramters
##	2: ID is not an integer
##	3: ID is not in master file
##	4: ID has no details

if [ ! $# -eq 1 ]
then
	echo "Invalid paramters"
	echo "Usage: ./sc15 ID"
	exit 1
fi

### Check if id is an integer
ID=$1
temp="^[0-9]+$"
if ! [[ $ID =~ $temp ]]
then
	echo "Invalid id format, must be an integer"
	exit 2
fi
### Check if id in the stinfo DB
QUERY=$(mysql -u non -pJava123$ -NB -e "select * from bash.stinfo where id = $ID")
if [ -z "$QUERY" ]
then
	echo "Error: db_stinfo has no ID, can not insert"
	exit 3
fi

#### Select from the DB the name and email
result=($(mysql -u non -pJava123$ -NB -e "select * from bash.stinfo where id = $ID"))
NAME=${result[1]}
EMAIL=${result[2]}
### REad the details

echo -n "the Customer with id : $ID ,  name : $NAME , email : $EMAIL , has bought with total : "

mysql -u non -pJava123$ -NB -e "select * from bash.stdetails where id =$ID " | awk 'BEGIN { C=0 } { C=C+$2 } END { print "the sum is " C}'


exit 0
